export const metadata = {
    title: "About - LIKELION",
    description: "Generated by create next app",
  };
import Image from "next/image";
  
  export default function About() {
    return <div className="mx-auto grid max-w-7xl p-8"> 
    <div className="py-4 px-1 lg:flex lg:gap-x-0 xl:gap-x-3">
        <div className="">
          <div className="hidden xl:mt-6 xl:w-60 2xl:w-64 xl:border xl:border-gray-200 xl:rounded-md xl:py-4 xl:px-3 xl:block xl:sticky xl:top-32 xl:h-fit ">
            <div className="custom-container">
               <div className="border-b-2 py-4">
                <div className="col-2 d-none d-lg-block position-relative">
                    <div className="flex justify-between items-center py-2.5 border-b-2 py-4">
                    <p className="">Filters</p>
                  <Image src="/Frame20.png" alt="" width={20} height={20} />
                  </div>
                  <div className="flex justify-between items-center py-2.5">
                    <p>T-shirts</p>
                  <Image src="/muitenn.png" alt="" width={20} height={20} />
                  </div>
                  <div className="flex justify-between items-center py-2.5">
                    <p>Shorts</p>
                  <Image src="/muitenn.png" alt="" width={20} height={20} />
                  </div>
                  <div className="flex justify-between items-center py-2.5">
                    <p>Hoodie</p>
                  <Image src="/muitenn.png" alt="" width={20} height={20} />
                  </div>
                  <div className="flex justify-between items-center py-2.5">
                    <p>Jeans</p>
                  <Image src="/muitenn.png" alt="" width={20} height={20} />
                  </div>
                  <div>
                  </div>
                </div>
              </div>
            </div>
            <div className="custom-container">
              <div className="border-b-2 py-4">
                <div className="col-2 d-none d-lg-block position-relative">
                  <div className="flex justify-between items-center py-2.5">
                  <p>Price</p>
                  <Image src="/muitenlen.png" alt="" width={20} height={20} />
                  </div>
                  <div className="py-2">
                  <Image src="/Group7.png" alt="" width={200} height={70} />
                  </div>
                </div>
              </div>
            </div>
            <div className="custom-container">
            <div className="border-b-2 py-4">
                <div className="col-2 d-none d-lg-block position-relative">
                <div className="flex justify-between items-center py-2.5">
                  <p>Color</p>
                  <Image src="/muitenlen.png" alt="" width={20} height={20} />
                  </div>
                  <div>
                  <Image src="/Frame89.png" alt="" width={200} height={70} />
                  </div>
                  </div>
            </div>
            </div> 
            <div className="custom-container">
              <div className="border-b-2 py-4">
                <div className="col-2 d-none d-lg-block position-relative">
                <div className="flex justify-between items-center py-2.5">
                  <p>Size</p>
                  <Image src="/muitenlen.png" alt="" width={20} height={20} />
                  </div>
                  <div>
                  <Image src="/size.png" alt="" width={200} height={70} />
                  </div>
                  </div>
                  </div>
            </div>
            <div className="custom-container">
              <div className="row">
                <div className="col-2 d-none d-lg-block position-relative">
                <div className="flex justify-between items-center py-2.5">
                  <p>Dress Style</p>
                  <Image src="/muitenlen.png" alt="" width={20} height={20} />
                  </div>
                  <div className="flex justify-between items-center py-2.5">
                    <p>Casual</p>
                  <Image src="/muitenn.png" alt="" width={20} height={20} />
                  </div>
                  <div className="flex justify-between items-center py-2.5">
                    <p>Formal</p>
                  <Image src="/muitenn.png" alt="" width={20} height={20} />
                  </div>
                  <div className="flex justify-between items-center py-2.5">
                    <p>Party</p>
                  <Image src="/muitenn.png" alt="" width={20} height={20} />
                  </div>
                  <div className="flex justify-between items-center py-2.5">
                    <p>Gym</p>
                  <Image src="/muitenn.png" alt="" width={20} height={20} />
                  </div>
                  </div>
                  </div>
            </div>
            
            <div>
                <button class="text-center bg-black border text-white py-3 px-12 font-medium text-sm rounded-full">Apply Filter</button>
            </div>
          </div>
        </div> 
        {/* cacsanpham */}
              <div className="w-full p-4 mt-3">
                <div className="">
                  <div className="flex justify-between py-2">
                  <p>Casual</p>
                  <div className="flex gap-2">
                  <p>Showing 1-10 of 100 Products</p>
                  <p>Sort by: <span className="font-semibold">Most Popular</span></p>
                  </div>
                  </div>
                  <div className="grid grid-cols-1 sm: md:grid-cols-2 xl:grid-cols-3 gap-6 w-full">
                    <div className="card">
                    <span>
                      <Image src="/a1.png" alt="" width={500} height={500} />
                    </span>
                      <div className="flex flex-col p-5"> 
                      <h3 className="text-lg text-black-100 font-semibold">T-shirt with Tape Deatails</h3>
                      <div>
                    <Image src="/rate.png" alt="" width={150} height={33} />
                      </div>
                      <p className="text-xl text-black-100 font-semibold">$212</p>
                        </div>
                    </div>
                    <div className="card">
                    <span>
                      <Image src="/a2.png" alt="" width={400} height={400} />
                    </span>
                      <div className="flex flex-col p-5"> 
                      <h3 className="text-lg text-black-100 font-semibold">T-shirt with Tape Deatails</h3>
                      <div>
                    <Image src="/rate.png" alt="" width={150} height={33} />
                      </div>
                      <p className="text-xl text-black-100 font-semibold">$212</p>
                        </div>
                    </div>
                    <div className="card">
                    <span>
                      <Image src="/a3.png" alt="" width={400} height={400} />
                    </span>
                      <div className="flex flex-col p-5"> 
                      <h3 className="text-lg text-black-100 font-semibold">T-shirt with Tape Deatails</h3>
                      <div>
                    <Image src="/rate.png" alt="" width={150} height={33} />
                      </div>
                      <p className="text-xl text-black-100 font-semibold">$212</p>
                        </div>
                    </div>
                    <div className="card">
                    <span>
                      <Image src="/a4.png" alt="" width={400} height={400} />
                    </span>
                      <div className="flex flex-col p-5"> 
                      <h3 className="text-lg text-black-100 font-semibold">T-shirt with Tape Deatails</h3>
                      <div>
                    <Image src="/rate.png" alt="" width={150} height={33} />
                      </div>
                      <p className="text-xl text-black-100 font-semibold">$212</p>
                        </div>
                    </div>
                    <div className="card">
                    <span>
                      <Image src="/a5.png" alt="" width={400} height={400} />
                    </span>
                      <div className="flex flex-col p-5"> 
                      <h3 className="text-lg text-black-100 font-semibold">T-shirt with Tape Deatails</h3>
                      <div>
                    <Image src="/rate.png" alt="" width={150} height={33} />
                      </div>
                      <p className="text-xl text-black-100 font-semibold">$212</p>
                        </div>
                    </div>
                    <div className="card">
                    <span>
                      <Image src="/a6.png" alt="" width={400} height={400} />
                    </span>
                      <div className="flex flex-col p-5"> 
                      <h3 className="text-lg text-black-100 font-semibold">T-shirt with Tape Deatails</h3>
                      <div>
                    <Image src="/rate.png" alt="" width={150} height={33} />
                      </div>
                      <p className="text-xl text-black-100 font-semibold">$212</p>
                        </div>
                    </div>
                    <div className="card">
                    <span>
                      <Image src="/a7.png" alt="" width={400} height={400} />
                    </span>
                      <div className="flex flex-col p-5"> 
                      <h3 className="text-lg text-black-100 font-semibold">T-shirt with Tape Deatails</h3>
                      <div>
                    <Image src="/rate.png" alt="" width={150} height={33} />
                      </div>
                      <p className="text-xl text-black-100 font-semibold">$212</p>
                        </div>
                    </div>
                    <div className="card">
                    <span>
                      <Image src="/a8.png" alt="" width={400} height={400} />
                    </span>
                      <div className="flex flex-col p-5"> 
                      <h3 className="text-lg text-black-100 font-semibold">T-shirt with Tape Deatails</h3>
                      <div>
                    <Image src="/rate.png" alt="" width={150} height={33} />
                      </div>
                      <p className="text-xl text-black-100 font-semibold">$212</p>
                        </div>
                    </div>
                    <div className="card">
                    <span>
                      <Image src="/a9.png" alt="" width={400} height={400} />
                    </span>
                      <div className="flex flex-col p-5"> 
                      <h3 className="text-lg text-black-100 font-semibold">T-shirt with Tape Deatails</h3>
                      <div>
                    <Image src="/rate.png" alt="" width={150} height={33} />
                      </div>
                      <p className="text-xl text-black-100 font-semibold">$212</p>
                        </div>
                    </div>
                  </div>
                </div>

              </div>

            

          


    </div>
    
    </div>;
  }
  