export const metadata = {
  title: "Contact - LIKELION",
  description: "Generated by create next app",
};
import Image from "next/image";

export default function Cart() {
  return <div>
    <div className="mx-auto grid max-w-7xl p-6">
      <div className="flex gap-3">
        <div className="flex gap-2">
        <h3 className="text-lg">Home</h3>
                <Image src="/muiten.png" alt="" width={20} height={20} />
                </div>
                <div className="flex gap-2">
                <h3 className="text-lg">Cart</h3>
                <Image src="/muiten.png" alt="" width={20} height={20} />
                </div> 
      </div>
      <div>
        <h2 className="mb-3 text-black-500 dark:text-black-500 text-3xl font-semibold sm:text-4xl">YOUR CART</h2>
      </div> 
      


        <div className="">
        <div className="xl:flex justify-between">
            <div className="border-2 rounded-lg max-w-2xl">
              <div className="card">
                <div className="flex space-x-7 sm:my-4 sm:py-8 px-4 border-b-2 "> 
                  <div className="">
                  <Image src="/cart1.png" alt="" width={200} height={200} />
                  </div>
                  <div className="">
                  <div className=" flex space-x-48 align-items-start mb-2">
                    <h6 className="text-xl text-black-100 font-semibold">Checkered Shirt</h6>
                  <Image src="/thungrac.png" alt="" width={20} height={20} />
                  </div>
                  <p className="d-block text-muted fw-bolder text-neutral-500">Size: Medium</p>
                  <p className="d-block text-muted fw-bolder text-neutral-500">Color: Red</p>
                  <div className="flex space-x-48 mt-4">
                  <p className="text-2xl font-semibold">$80</p>
                  <Image src="/add.png" alt="" width={100} height={20} />
                </div>

                  </div>
                </div>  
              </div>
              <div className="card">
                <div className="flex space-x-7 sm:my-4 sm:py-8 px-4 border-b-2 "> 
                  <div className="">
                  <Image src="/cart2.png" alt="" width={200} height={200} />
                  </div>
                  <div className="">
                  <div className=" flex space-x-48 align-items-start mb-2">
                    <h6 className="text-xl text-black-100 font-semibold">Checkered Shirt</h6>
                  <Image src="/thungrac.png" alt="" width={20} height={20} />
                  </div>
                  <p className="d-block text-muted fw-bolder text-neutral-500">Size: Medium</p>
                  <p className="d-block text-muted fw-bolder text-neutral-500">Color: Red</p>
                  <div className="flex space-x-48 mt-4">
                  <p className="text-2xl font-semibold">$80</p>
                  <Image src="/add.png" alt="" width={100} height={20} />
                </div>

                  </div>
                </div>  
              </div>
              <div className="card">
                <div className="flex space-x-7 sm:my-4 sm:py-8 px-4 border-b-2 "> 
                  <div className="">
                  <Image src="/cart3.png" alt="" width={200} height={200} />
                  </div>
                  <div className="">
                  <div className=" flex space-x-48 align-items-start mb-2">
                    <h6 className="text-xl text-black-100 font-semibold">Checkered Shirt</h6>
                  <Image src="/thungrac.png" alt="" width={20} height={20} />
                  </div>
                  <p className="d-block text-muted fw-bolder text-neutral-500">Size: Medium</p>
                  <p className="d-block text-muted fw-bolder text-neutral-500">Color: Red</p>
                  <div className="flex space-x-48 mt-4">
                  <p className="text-2xl font-semibold">$80</p>
                  <Image src="/add.png" alt="" width={100} height={20} />
                </div>

                  </div>
                </div>  
              </div>
            </div>
            <div className=" flex-grow bottom-0 left-0 right-0 md:top-36 shadow-lg border-2 rounded-lg py-4 xl:py-12 px-4 xl:px-8 -mx-[1rem] md:mx-4 xl:mx-4 md:w-auto md:min-w-[300px] md:max-w-[600px] ">
              <div classNamelass="">
              <h6 className="text-xl text-black-100 font-semibold">Order Summary</h6>
              </div>
              <div className="py-5 border-b-2">
                <div className="flex justify-between">
                  <p className="text-neutral-500">Subtotal</p>
                  <p className="text-xl text-black-100 font-semibold">$565</p>
                </div>
                <div className="flex justify-between">
                  <p className="text-neutral-500">Discount (-20%)</p>
                  <p className="text-xl text-red-500 font-semibold">-$113</p>
                </div>
                <div className="flex justify-between">
                  <p>Delivery Fee</p>
                  <p className="text-xl text-black-100 font-semibold">15$</p>
                </div>
              </div>  
              <div className="flex justify-between py-3">
                <p className="text-neutral-500">Total</p>
                <p className="text-2xl text-black-100 font-semibold">$467</p>
              </div> 
              <div className="py-4">
                <div className="flex justify-between">
                <input class=" rounded-full px-3 py-4 bg-slate-100  focus:outline-none w-80 text-sm focus:border-gray-400" type="text" placeholder="Add promo code" value=""/>
                <button class="bg-black border text-white py-3 px-12 font-medium text-sm rounded-full">Apply</button>
                </div>
              </div>
              <div className="py-4">
              <a href="" class=" text-center block w-full bg-black border text-white py-3 px-8 font-medium text-sm rounded-full" role="button">Go to checkout</a>
              </div>
            </div>
        </div>  
        </div>
        </div>
    

  </div>;
}
